version: "3"
services:
  prometheus:
    image: prom/prometheus
    networks:
      - prometheus
      - traefik
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: google/cadvisor:latest
    networks:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  node-exporter:
    image: prom/node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points=^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)
      - --collector.filesystem.ignored-fs-types=^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$
    networks:
      - prometheus
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    networks:
      - prometheus
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
      - ${ALERTMANAGER_STORAGE_FOLDER}:/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  karma:
    image: lmierzwa/karma:v0.56
    environment:
      - ALERTMANAGER_URI=http://alertmanager:9093
    networks:
      - prometheus
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.karma.rule=Host(`${KARMA_DOMAIN}`)
        - traefik.http.routers.karma.entryPoints=https
        - traefik.http.routers.karma.tls=true
        - traefik.http.routers.karma.tls.certresolver=letsencrypt
        - traefik.http.services.karma.loadbalancer.server.port=8080

networks:
  prometheus:
  traefik:
    external: true
