global:
# How frequently to scrape targets by default.
# [ scrape_interval: <duration> | default = 1m ]

# How long until a scrape request times out.
# [ scrape_timeout: <duration> | default = 10s ]

# How frequently to evaluate rules.
# [ evaluation_interval: <duration> | default = 1m ]

# The labels to add to any time series or alerts when communicating with
# external systems (federation, remote storage, Alertmanager).
# external_labels:
#   [ <labelname>: <labelvalue> ... ]

# File to which PromQL queries are logged.
# Reloading the configuration will reopen the file.
# [ query_log_file: <string> ]

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
# rule_files:
#   [ - <filepath_glob> ... ]

# A list of scrape configurations.
scrape_configs:
  - job_name: "traefik"
    dns_sd_configs:
      - names: ["tasks.traefik"]
        type: A
        port: 8082
  - job_name: "cadvisor"
    dns_sd_configs:
      - names: ["tasks.cadvisor"]
        type: A
        port: 8080
  - job_name: "node-exporter"
    dns_sd_configs:
      - names: ["tasks.node-exporter"]
        type: A
        port: 9100
# Alerting specifies settings related to the Alertmanager.
# alerting:
#   alert_relabel_configs:
#     [ - <relabel_config> ... ]
#   alertmanagers:
#     [ - <alertmanager_config> ... ]

# Settings related to the remote write feature.
# remote_write:
#   [ - <remote_write> ... ]

# Settings related to the remote read feature.
# remote_read:
#   [ - <remote_read> ... ]
