global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "rasaro"

# File to which PromQL queries are logged.
# Reloading the configuration will reopen the file.
# [ query_log_file: <string> ]

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "traefik"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ["tasks.traefik"]
        type: A
        port: 8082
  - job_name: "cadvisor"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ["tasks.cadvisor"]
        type: A
        port: 8080
  - job_name: "node-exporter"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ["tasks.node-exporter"]
        type: A
        port: 9100

alerting:
  alertmanagers:
    - dns_sd_configs:
        - names: ["tasks.alertmanager"]
          type: A
          port: 9093
